// Integrate atelier sprite specs (final/*.json) into src/art/sprites_hd.js.
// Usage: node tools/integrate-hd.mjs <dir-with-final-jsons>
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';

const dir = process.argv[2];
if (!dir) { console.error('usage: node tools/integrate-hd.mjs <dir>'); process.exit(1); }

const CHAR_IDS = new Set(['adric', 'evlann', 'hemer', 'corlan', 'vielna', 'samuel', 'mina', 'voll', 'rahshiel', 'noin']);
const BOSS_IDS = new Set(['anlo', 'mimi', 'whale', 'rahshielBoss', 'finalis', 'margola', 'lambking', 'mother']);

const chars = {}, enemies = {}, bosses = {};
const problems = [];
for (const f of readdirSync(dir).filter(x => x.endsWith('.json'))) {
  const spec = JSON.parse(readFileSync(join(dir, f), 'utf8'));
  for (const s of spec.sprites || []) {
    const isChar = CHAR_IDS.has(s.id), isBoss = BOSS_IDS.has(s.id);
    const target = isChar ? chars : isBoss ? bosses : enemies;
    const cell = isBoss ? 3 : 2;
    // validate: widths consistent, only known/overridden palette chars
    const w = Math.max(...s.rows.map(r => r.length));
    for (const [tag, rows] of [['rows', s.rows], ['rowsB', s.rowsB]]) {
      if (!rows) { if (tag === 'rowsB') problems.push(`${f}:${s.id} missing rowsB`); continue; }
      const ww = Math.max(...rows.map(r => r.length));
      if (ww !== w) problems.push(`${f}:${s.id} ${tag} width ${ww} != ${w}`);
    }
    if (target[s.id]) problems.push(`${f}:${s.id} DUPLICATE — overwriting`);
    target[s.id] = { rows: s.rows, rowsB: s.rowsB, cell, ...(s.pal ? { pal: s.pal } : {}) };
  }
}

const emit = (obj) => JSON.stringify(obj, null, 1)
  .replace(/"([A-Za-z_][A-Za-z0-9_]*)":/g, '$1:');

const out = `// HD sprite redraws from the art ateliers — GENERATED by tools/integrate-hd.mjs, do not hand-edit.
// Shape: { id: { rows: [...], rowsB: [...], pal?: {}, cell: 2|3 } }
export const CHAR_HD = ${emit(chars)};
export const ENEMY_HD = ${emit(enemies)};
export const BOSS_HD = ${emit(bosses)};
`;
writeFileSync('src/art/sprites_hd.js', out);
console.log(`chars=${Object.keys(chars).length} enemies=${Object.keys(enemies).length} bosses=${Object.keys(bosses).length}`);
if (problems.length) { console.log('PROBLEMS:\n' + problems.join('\n')); process.exit(2); }
